version: '3.8'
services:
  database:
    image: postgres:15
    container_name: csv_postgres
    restart: always
    #env_file:
    #  - .env
    environment:
      POSTGRES_DB: csv_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: csv_backend
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    command: npm run dev
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/csv_db
      - PORT=5000
      - HOST=0.0.0.0
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: csv_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    command: npm run dev
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - app-network

volumes:
  node_modules:
  pgdata:

networks:
  app-network:
    driver: bridge